baseURL = 'https://www.kameiworks.com/'
languageCode = 'ja-jp'
title = 'かめいが作ったのここ置いとくわ――ウェブ漫画・小説・イラスト'
theme = "ananke"


[params]
  # CSSを上書きするためのカスタムCSSファイルを指定
  custom_css = ["css/custom.css"]

# hugo.toml の場合
[markup.goldmark.renderer]
  # ⬇️ この設定で、Markdown内のHTMLタグが有効になります ⬇️
  unsafe = true

# メインメニューの設定
[[menu.main]]
  name = "ホーム"         # リンクの表示名
  url = "/"              # リンク先 (トップページ)
  weight = 1             # 表示順 (数字が小さいほど左/上)


[[menu.main]]
  name = "このサイトについて"
  url = "/about/"
  weight = 4

[[menu.main]]
  name = "お問い合わせ"
  url = "/contact/"
  weight = 5

  [[menu.main]]
  name = "プライバシーポリシー"
  url = "/privacy/"
  weight = 3