backend:
  name: github  # ← バックエンド名を 'github' に変更
  branch: main
  repo: "kameiworks/kameiworks" # ← ★必須：GitHubのユーザー名とリポジトリ名を指定

media_folder: "static/images" # 画像ファイルをGitリポジトリのどこに保存するか
public_folder: "/images"      # サイトの公開URLで画像にアクセスする時のパス

# CMSでの編集対象となるコンテンツのコレクション設定
collections:
  - name: "blog" # CMSで表示されるコレクション名
    label: "作品/記事" # ユーザーに表示されるラベル
    folder: "content/posts" # HugoのMarkdownファイルが格納されているフォルダ
    create: true # 新規記事作成を許可
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # ファイル名の形式 (Hugoの命名規則に合わせる)
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime"}
      - {label: "概要 (Description)", name: "description", widget: "string"}
      - {label: "本文", name: "body", widget: "markdown"}